/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DiffComponent: typeof import('./src/components/config/DiffComponent.vue')['default']
    Foo: typeof import('./src/components/Foo.vue')['default']
    LangSwitch: typeof import('./src/components/LangSwitch.vue')['default']
    McpServerDetailComponent: typeof import('./src/components/mcpserver/McpServerDetailComponent.vue')['default']
    McpServerHistoryList: typeof import('./src/components/mcpserver/McpServerHistoryList.vue')['default']
    McpServerToolItem: typeof import('./src/components/mcpserver/McpServerToolItem.vue')['default']
    McpServerValueComponent: typeof import('./src/components/mcpserver/McpServerValueComponent.vue')['default']
    McpToolComponent: typeof import('./src/components/mcpserver/McpToolComponent.vue')['default']
    MoreSetting: typeof import('./src/components/MoreSetting.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NamespacePopSelect: typeof import('./src/components/namespace/NamespacePopSelect.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NUpload: typeof import('naive-ui')['NUpload']
    ResetPassword: typeof import('./src/components/user/ResetPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouteRuleDisplay: typeof import('./src/components/mcpserver/RouteRuleDisplay.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SubContentFullPage: typeof import('./src/components/common/SubContentFullPage.vue')['default']
    ToolConfigList: typeof import('./src/components/mcpserver/ToolConfigList.vue')['default']
    ToolDetailDisplay: typeof import('./src/components/mcpserver/ToolDetailDisplay.vue')['default']
    ToolEditForm: typeof import('./src/components/mcpserver/ToolEditForm.vue')['default']
    ToolSpecSelector: typeof import('./src/components/mcpserver/ToolSpecSelector.vue')['default']
  }
}
